version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pdfkit
    versions:
    - 0.12.0
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: archiver
    versions:
    - 5.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: svgson
    versions:
    - 4.1.0
  registries:
  - npm-registry-registry-npmjs-org
