name: NRK Core Icons

headHtml: |
  <script src="core-icons.min.js"></script>
  <link rel="stylesheet" href="docs.css">

assets:
  - docs.css          # Include CSS for documentation
  - docs.js          # Include JS for documentation
  - core-icons.js     # Include core icons
  - core-icons.min.js # Include core icons minified
  - pdfkit-and-blob-stream.js # Include PDFKit

sidebar:
  background: "#3d2351"
  textColor: "#fff"

order:
  - Introduction
  - Layout
