name: Build and test package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: ./.github/actions/setup

      - name: Build project
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
