name: Figma sync

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - 'figma:LIBRARY_PUBLISH'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync assets from Figma and create pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: ./.github/actions/setup

      - name: Sync assets from Figma
        run: ./bin/cli sync
        env:
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}

      - name: Run tests
        run: npm run test

      - name: Commit changes to `figma-sync` branch
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: figma-sync
          create_branch: true
          commit_user_name: 'Figma sync workflow'
          commit_message: 'Sync assets from Figma'
          push_options: '--force'
          skip_dirty_check: false

      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head figma-sync \
            --title 'Sync assets from Figma' \
            --body 'This pull request contains the latest assets synced from Figma.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
